# Generated by Django 3.0.8 on 2020-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ManyToManyField(to='main.Artist')),
            ],
        ),
    ]
